name: 'Deploy Azure infra using Terraform'
on:
  push:
    branches:
      - 'feature/*'
      - 'main'
    paths:
      - 'infra'
      - '.github/workflows/deploy-infra-main.yml'
jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.6.5"