name: 'Deploy Azure infra using Terraform'
on:
  push:
    branches:
      - 'feature/**'
      - 'main'
    paths:
      - 'infra/**'
      - '.github/workflows/deploy-infra-main.yml'
jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.6.5"
      - name: Linting
        run: terraform fmt -check -diff -recursive . 
  deploy_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: code_checks
    env: 
      ENVIRONMENT: 'dev'
      STATE_RESOURCE_GROUP_NAME: 'rg-state-dtype-dev'
      STATE_STORAGE_ACCOUNT_NAME: 'stdtypestatedev'
      STATE_CONTAINER_NAME: 'state'
      STATE_FILE_NAME: 'state.tfstate'
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Az login
        uses: azure/login@v1
        with:
         creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Ensure TF state
        shell: pwsh
        run: ./infra/setup-terraform-state.ps1 -env ${{env.ENVIRONMENT}} -subscriptionId $${{env.ARM_SUBSCRIPTION_ID}} -resourceGroupName ${{env.STATE_RESOURCE_GROUP_NAME}} -storageAccountName ${{env.STATE_STORAGE_ACCOUNT_NAME}} -containerName ${{env.STATE_CONTAINER_NAME}}
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.6.5"
      - name: 'Terraform Init'
        run: | 
          terraform init -backend-config="resource_group_name=${{env.STATE_RESOURCE_GROUP_NAME}}" -backend-config="storage_account_name=${{env.STATE_STORAGE_ACCOUNT_NAME}}" -backend-config="container_name=${{env.STATE_CONTAINER_NAME}}" -backend-config="key=${{env.STATE_FILE_NAME}}" 
        working-directory: infra
      - name: 'Terraform Plan'
        run: |
          terraform plan -var-file="tfvars/dev.tfvars" -var="service_principal_name=Github" -var="service_principal_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
        working-directory: infra
      - name: Manual validation
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: jacovg91
          minimum-approvals: 1
      - name: 'Terraform apply'
        run: |
          terraform apply --auto-approve -var-file="tfvars/dev.tfvars" -var="service_principal_name=Github" -var="service_principal_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
        working-directory: infra
  deploy_prd:
    runs-on: ubuntu-latest
    needs: code_checks
    if: github.ref == 'refs/heads/main' # only run this job from the main branch. 
    env: 
      ENVIRONMENT: 'prd'
      STATE_RESOURCE_GROUP_NAME: 'rg-state-dtype-prd'
      STATE_STORAGE_ACCOUNT_NAME: 'stdtypestateprd'
      STATE_CONTAINER_NAME: 'state'
      STATE_FILE_NAME: 'state.tfstate'
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Az login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Ensure TF state
        shell: pwsh
        run: ./infra/setup-terraform-state.ps1 -env ${{env.ENVIRONMENT}} -subscriptionId $${{env.ARM_SUBSCRIPTION_ID}} -resourceGroupName ${{env.STATE_RESOURCE_GROUP_NAME}} -storageAccountName ${{env.STATE_STORAGE_ACCOUNT_NAME}} -containerName ${{env.STATE_CONTAINER_NAME}}
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.5"
      - name: 'Terraform Init'
        run: | 
          terraform init -backend-config="resource_group_name=${{env.STATE_RESOURCE_GROUP_NAME}}" -backend-config="storage_account_name=${{env.STATE_STORAGE_ACCOUNT_NAME}}" -backend-config="container_name=${{env.STATE_CONTAINER_NAME}}" -backend-config="key=${{env.STATE_FILE_NAME}}" 
        working-directory: infra
      - name: 'Terraform apply'
        run: |
          terraform apply --auto-approve -var-file="tfvars/prd.tfvars" -var="service_principal_name=Github" -var="service_principal_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
        working-directory: infra
      
