name: Deploy Azure infra using Terraform
on:
  push:
    paths:
      - 'infra'
      - '.github/workflows/'
      - '.github/workflows/deploy-infra-env.yml'
    branches:
      - '*'
jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2