name: 'Deploy Azure infra using Terraform'
on:
  push:
    branches:
      - 'feature/*'
      - 'main'
    paths:
      - 'infra/*'
      - '.github/workflows/deploy-infra-main.yml'
jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.6.5"
      - name: Linting
        run: terraform fmt -check -diff -recursive . 
  deploy_dev:
    runs-on: ubuntu-latest
    needs: code_checks
    env: 
      ENVIRONMENT: 'dev'
      STATE_RESOURCE_GROUP_NAME: 'rg-dtype-state-dev'
      STATE_STORAGE_ACCOUNT_NAME: 'stdtypestatedev'
      STATE_CONTAINER_NAME: 'state'
      STATE_FILE_NAME: 'state.tfstate'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Az login
        uses: azure/login@v1
        with:
         creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Ensure TF state
        shell: pwsh
        run: ./infra/setup-terraform-state.ps1 -env ${{env.ENVIRONMENT}} -resourceGroupName ${{env.STATE_RESOURCE_GROUP_NAME}} -storageAccountName ${{env.STATE_STORAGE_ACCOUNT_NAME}} -containerName ${{env.STATE_CONTAINER_NAME}}
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.6.5"
      - name: 'Terraform Init'
        run: | 
          cd infra
          terraform init -var-file="tfvars/dev.tfvars"
      - name: 'Terraform Plan'
        run: |
          cd infra
          terraform plan -var-file="tfvars/dev.tfvars"
      