name: 'Deploy Azure infra using Terraform'
on:
  push:
    branches:
      - 'feature/*'
      - 'main'
    paths:
      - 'infra'
      - '.github/workflows/deploy-infra-main.yml'
jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.6.5"
      - name: Linting
        run: terraform fmt -check -diff -recursive . 
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      # - name: Ensure TF remote state
      #   run: infra/setup-terraform-state.ps1
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'