name: 'Deploy Azure infra using Terraform'
on:
  push:
    branches:
      - '*'
jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        